// AUTO-GENERATED by admin tool. Hand edits will be overwritten.
// Source of truth: portfolio admin at http://localhost:3000/admin

const techStack = [
    {
        "name": "Unity",
        "icon": "fab fa-unity",
        "projects": [
            "from-the-ashes",
            "strictly-human",
            "mr-bubbles",
            "displaced"
        ]
    },
    {
        "name": "Substance Painter",
        "icon": "assets/icons/SubstancePainterGray.png",
        "projects": [
            "mr-bubbles",
            "displaced"
        ]
    },
    {
        "name": "Steamworks SDK",
        "icon": "fab fa-steam",
        "projects": [
            "displaced"
        ]
    },
    {
        "name": "Git",
        "icon": "fab fa-git-alt",
        "projects": [
            "mr-bubbles",
            "displaced"
        ]
    },
    {
        "name": "Python",
        "icon": "fab fa-python",
        "projects": []
    },
    {
        "name": "C#",
        "icon": "assets/icons/csharpGray.png",
        "projects": [
            "from-the-ashes",
            "strictly-human",
            "mr-bubbles",
            "displaced"
        ]
    },
    {
        "name": "Blender",
        "icon": "assets/icons/blender.ico",
        "projects": [
            "mr-bubbles",
            "displaced"
        ]
    },
    {
        "name": "FL Studio",
        "icon": "assets/icons/FLGray.png",
        "projects": [
            "strictly-human",
            "mr-bubbles"
        ]
    },
    {
        "name": "Wwise",
        "icon": "assets/icons/wwiseGray.png",
        "projects": [
            "displaced"
        ]
    }
];

const imageInventory = {
    "displaced": {
        "thumbnail": "assets/Displaced/thumbnailPhoto.png",
        "displayImages": [
            "assets/Displaced/displayPhoto_1.png",
            "assets/Displaced/displayPhoto_2.png",
            "assets/Displaced/displayPhoto_3.png"
        ]
    },
    "mr-bubbles": {
        "thumbnail": "assets/MrBubbles/thumbnailPhoto.png",
        "displayImages": [
            "assets/MrBubbles/displayPhoto_1.png",
            "assets/MrBubbles/displayPhoto_2.png",
            "assets/MrBubbles/displayPhoto_3.png"
        ]
    },
    "from-the-ashes": {
        "thumbnail": "assets/FromTheAshes/thumbnailPhoto.png",
        "displayImages": [
            "assets/FromTheAshes/displayPhoto_1.png",
            "assets/FromTheAshes/displayPhoto_2.png",
            "assets/FromTheAshes/displayPhoto_3.png"
        ]
    },
    "strictly-human": {
        "thumbnail": "assets/StrictlyHumanAffair/thumbnailPhoto.jpeg",
        "displayImages": [
            "assets/StrictlyHumanAffair/displayPhoto_1.jpg",
            "assets/StrictlyHumanAffair/displayPhoto_2.jpg",
            "assets/StrictlyHumanAffair/displayPhoto_3.jpg",
            "assets/StrictlyHumanAffair/displayPhoto_4.jpg"
        ]
    }
};

const projects = [
    {
        "id": "from-the-ashes",
        "assetFolder": "FromTheAshes",
        "type": "gamejam",
        "duration": "1 Week",
        "youtubeUrls": [],
        "title": "From The Ashes",
        "description": "A Multiplayer Horror, scour the area, and return safely.",
        "image": "fas fa-gamepad",
        "thumbnailUrl": null,
        "tech": [
            "Unity",
            "C#"
        ],
        "featured": false,
        "detailsEnabled": false,
        "media": [],
        "overview": {
            "description": "The Phon is designed with the ability not to die, but rather to adapt to the method by which it was hurt. Knock it over for a short duration before it stands up with better tools in its arsenal. To handle melee weapons, it will develop ranged weapons, and to meet ranged weapons with armor.\n\n",
            "platforms": [
                "Windows",
                "Mac",
                "Linux"
            ],
            "status": "Released",
            "role": "Lead Dev",
            "storeUrl": "https://dev-stynt.itch.io/from-the-ashes-they-rise"
        },
        "details": {
            "challenges": [],
            "solutions": [],
            "lessons": [],
            "sections": []
        },
        "mediaCaptions": {},
        "mediaOrder": [],
        "mediaCompare": {}
    },
    {
        "id": "strictly-human",
        "assetFolder": "StrictlyHumanAffair",
        "type": "gamejam",
        "duration": "72 Hours",
        "youtubeUrls": [],
        "title": "A Strictly Human Affair",
        "description": "A first person, social puzzle game. Explore the train, collect items, and learn the secrets each passenger holds. ",
        "image": "fas fa-gamepad",
        "thumbnailUrl": null,
        "tech": [
            "Unity",
            "C#",
            "FL Studio"
        ],
        "featured": false,
        "detailsEnabled": false,
        "media": [],
        "overview": {
            "description": "When the train conductor is found brutally murdered, Sheriff Horace; trapped in a rolling prison alongside six other passengers, must reveal the monstrous killer from behind their mask.\n\nDevelopment focused on a mix of Dialogue and Interactions players would take outside. ",
            "platforms": [
                "Windows",
                "Linux",
                "Mac"
            ],
            "status": "Released",
            "role": "Developer",
            "storeUrl": "https://ratth3cat.itch.io/a-strictly-human-affair"
        },
        "details": {
            "challenges": [],
            "solutions": [],
            "lessons": [],
            "sections": []
        },
        "mediaCaptions": {},
        "mediaCompare": {}
    },
    {
        "id": "mr-bubbles",
        "assetFolder": "MrBubbles",
        "type": "gamejam",
        "duration": "72 Hours",
        "youtubeUrls": [
            "https://youtu.be/qXJDq9WIIj8"
        ],
        "detailsEnabled": false,
        "title": "Mr. Bubbles Car Wash",
        "description": "A charming cleaning simulation game where players manage a car wash business with whimsical characters.",
        "image": "fas fa-car",
        "thumbnailUrl": null,
        "tech": [
            "Unity",
            "C#",
            "Substance Painter",
            "Git",
            "Blender",
            "FL Studio"
        ],
        "featured": true,
        "media": [],
        "overview": {
            "description": "Mr. Bubbles Car Wash combines business simulation with subtle character-driven storytelling.",
            "platforms": [
                "Windows",
                "Itch.io"
            ],
            "status": "Released",
            "role": "Programmer, Sound Artist",
            "storeUrl": "https://qrypt.itch.io/mr-bubbles-car-salon"
        },
        "details": {
            "challenges": [
                "Creating an immersive dirt decal system",
                "Creating engaging characters within a simple business premise",
                "Designing satisfying progression systems that encourage long-term play",
                "The implementation of systems designed. Code Was ready, yet implementation takes time"
            ],
            "solutions": [
                "A Render Based decal Stamp and collision detection to spawn and clean dirt",
                "Used Blender and Substance Painter to create basic car-wash environment",
                "Designed a procedural and modular dirt generation and cleaning system"
            ],
            "lessons": [
                "Don't wait until the final moment to think about how you will create a tutorial",
                "Feedback is critical, but a problem has multiple solutions",
                "Ensure Polish on elements possessed rather than attempting to produce rushed concepts."
            ],
            "sections": []
        },
        "mediaOrder": [
            "image:assets/MrBubbles/displayPhoto_1.png",
            "youtube:qXJDq9WIIj8",
            "image:assets/MrBubbles/displayPhoto_2.png",
            "image:assets/MrBubbles/displayPhoto_3.png"
        ],
        "mediaCaptions": {},
        "mediaCompare": {}
    },
    {
        "id": "displaced",
        "assetFolder": "Displaced",
        "type": "project",
        "youtubeUrls": [
            "https://www.youtube.com/watch?v=d8_cd5z4ysw"
        ],
        "detailsEnabled": true,
        "title": "Displaced",
        "description": "A First Person Multiplayer FPS, fight across two dimensions to conquer reality, and survive the oncoming apocalypse.",
        "image": "fas fa-gamepad",
        "thumbnailUrl": null,
        "tech": [
            "Unity",
            "C#",
            "Substance Painter",
            "Steamworks SDK",
            "Git",
            "Blender",
            "Wwise"
        ],
        "featured": false,
        "media": [],
        "overview": {
            "description": "Displaced takes place across two realities, fighting for control. Players must switch between these realities mid-fight, which changes their positioning but offers ways in which they can surprise their enemies.\n\nDisplaced offers a unique team shooter dynamic where players have the ability to better navigate the map. The ability to swap dimensions prevents the feeling of getting fully stuck in tight, narrow areas or getting camped. \n\n- 50+ Playtesters\n- 49 Released Patches\n- 1000+ Hours of Development",
            "platforms": [
                "PC",
                "Steam"
            ],
            "status": "In Development",
            "role": "Lead Developer",
            "storeUrl": null
        },
        "details": {
            "challenges": [],
            "solutions": [],
            "lessons": [],
            "sections": [
                {
                    "title": "Designing the Gameplay",
                    "feature": "The Unique Gameplay",
                    "pages": [
                        {
                            "title": "The Mechanic",
                            "blocks": [
                                {
                                    "type": "text",
                                    "body": "One of the largest sources of inspiration for the Design of the mechanic is the game Titanfall 2, and the specific mechanic from the level Effect and Cause, commonly known as the \"Time Travel Mission\". \n\nBeing able to swap between two variations of the same map and maneuver through the level was not only jaw-dropping, but could create some genuinely interesting interactions between the player mechanics and the map design as well. It was unfortunate, however, to see a pretty toned-down, and ultimately a different thing entirely, in the multiplayer side. I noted a few reasons why.\n\n- Players move so fast that having to maintain track of players in the same world was already hard enough\n- Being a giant not only makes you a large target, but also creates large blind spots\n- The maps are generally quite open, meaning the linear effect that can't be catered to\n- It's not the point of the game.\n\nSo I asked myself: what if it was? I would need to make a more toned-down, smaller area for players to swap between these two dimensions, and have it be the focus of the game. "
                                },
                                {
                                    "type": "video",
                                    "url": "https://youtu.be/XOY4tV5thT0",
                                    "caption": ""
                                },
                                {
                                    "type": "text",
                                    "body": "With a very clear reference for how it was supposed to work, it wasn't long before I was able to produce a basic prototype. Some ideas were tested to see how other players would perceive this mechanic. Placeable portals were conceptualized; however, with its similarity to Splitgate and the importance of trying to keep the mechanic as simple as possible, an instant action was selected."
                                }
                            ]
                        },
                        {
                            "title": "The Experience",
                            "blocks": [
                                {
                                    "type": "text",
                                    "body": "When designing the experience, it was important to ask: What is a Displaced player doing? How do they move through the battlefield? What does the battlefield look like? What is their objective?\n\nWith this knowledge, it helps create the best experience and creates a set of rules that can later be used to the fullest, or in some cases broken. \n\nMovement:\n- First Person Walking and Jumping\n- Sprinting\n- Sliding\n- Two Charges of Dimension Traversal - Move the player to a duplicate copy of the world with small differences\n- Fatigue - Running or sliding in succession causes that movement tool to be less impactful.\n\nGunplay\n- Unique to their character\n- Not Inaccurate Due to Movement\n- Spread and Recoil\n- No Friendly Fire\n- No Penetration\n- Infinite Reserve Ammo\n\nMap Designs\n- Two Dimensions. \n- Formula: What if X did or didn't happen?\n- Dimension-Specific Obstacles or \"Irregularities\"\n\nObjective\n- Capture Points\n- Payloads\n- Elimination Targets"
                                }
                            ]
                        },
                        {
                            "title": "Extras",
                            "blocks": [
                                {
                                    "type": "text",
                                    "body": "How Much Info Do Players Have?\n\nThe point of swapping Dimensions is to use the lack of your enemies' knowledge of your position to gain tactical advantages. Given that, it was easy to ensure that you knew where your own team was. However, to know if an enemy was there, a lot of back and forth needed to occur. Later, settling on a slight indicator when an enemy is directly atop you. This knowledge doesn't severely change your advantage, but it will alert the enemy if you are directly atop them. "
                                },
                                {
                                    "type": "image",
                                    "path": "assets/Displaced/Breakdown/breakdown_mudai3u1ojfy.png",
                                    "caption": "Players See Ghosts of Allies in the Opposing Dimension",
                                    "mode": "normal",
                                    "afterPath": "",
                                    "beforeLabel": "",
                                    "afterLabel": ""
                                },
                                {
                                    "type": "video",
                                    "url": "https://youtu.be/5VdWGXD4z-I",
                                    "caption": "Enemies have a Humm and Yellow Indicator"
                                },
                                {
                                    "type": "text",
                                    "body": "How Does Sound Work?\n\nUnity has built-in audio; however, its spatialization leaves much to be desired. When a sound is played, it's critical that a player can identify where that sound originated from. Hearing things in a way that flattens it all out to a general direction isn't how we perceive noises. With that knowledge, it was critical to use tools like Wwise to implement spatially aware sound to ensure that sound interacted with the world in an expected and accurate way. "
                                },
                                {
                                    "type": "video",
                                    "url": "https://youtu.be/YQDVwip9Qbs",
                                    "caption": "Wwise Integration"
                                }
                            ]
                        }
                    ]
                },
                {
                    "title": "Designing the Characters",
                    "feature": "The Different Characters",
                    "pages": [
                        {
                            "title": "Overview",
                            "blocks": [
                                {
                                    "type": "text",
                                    "body": "The design of the characters came from a mix of experience, preference, and necessity.\n\nThe experience I have is from a background in Hero Shooters. The games I have the most hours in are Overwatch, Valorant, and Marvel Rivals. Due to this, it wasn't a stretch for me to design with those games and understand what I would need to have the completed game.\n\nFinally, the reason it needed to be a hero shooter was that I didn't want to make a plethora of guns, animations, and other elements on a limited budget. The resources I already had access to were a selection of character models, and I chose to make those characters unique and meet a fantasy, rather than a player's self-insert. \n\nThroughout the development of the characters' kits, a lot of issues would arise. The following chapters will break down the characters' kits, why they failed, and how they were redesigned. "
                                }
                            ]
                        },
                        {
                            "title": "The Original Kits",
                            "blocks": [
                                {
                                    "type": "text",
                                    "body": "--------------------------------------------------------------------------------------------------------------------------\nGhant\n\nGhant was an attempt at making my generic character. Someone who didn't have a complex kit and would allow those with different backgrounds to pick up the unique mechanic without stress. \n\nHis Ability was to provide an Adrenaline rush, granting improvements to speed, fire rate, and reload speed. "
                                },
                                {
                                    "type": "video",
                                    "url": "https://youtu.be/qn4-2uRDmF4",
                                    "caption": "Ghant Ability Demo"
                                },
                                {
                                    "type": "text",
                                    "body": "His Ultimate was a way to make him a glass cannon. Using it would set his health to a low percentage and boost his aforementioned stats, including regen rate, for a duration.\n\n"
                                },
                                {
                                    "type": "video",
                                    "url": "https://youtu.be/tDMltBl_cCk",
                                    "caption": "Ghant Ultimate Demo"
                                },
                                {
                                    "type": "text",
                                    "body": "--------------------------------------------------------------------------------------------------------------------------\nHuntress\n\nHuntress was designed as someone who would want to focus on one person and do anything in order to get them. This person would have good target priority, ultimate tracking, and positioning awareness. \n\nHuntress had an increased cooldown on her own ability to swap dimensions, and would thus need to rely more on her other abilities to get around.\n\nHuntress' ability was Hijack. This ability allows Huntress to walk up to any other person's breach and hijack it. This would move Huntress to the other dimension without wasting her personal dimension charge. "
                                },
                                {
                                    "type": "video",
                                    "url": "https://youtu.be/a1Temvyzu1M",
                                    "caption": "Huntress Ability Demo"
                                },
                                {
                                    "type": "text",
                                    "body": "Huntress' Ultimate was known as Dimensional Network. This ultimate created a bunch of open breaches, denoted by their green color. These breaches allowed for the free traversal of anyone. The aim of this ability would be that it either help Huntress chase her targets or lull them into a false sense of security by taking the breaches and running right into her. "
                                },
                                {
                                    "type": "video",
                                    "url": "https://youtu.be/k7J9ZKcgmN0",
                                    "caption": "Huntress Ultimate Demo"
                                },
                                {
                                    "type": "text",
                                    "body": "--------------------------------------------------------------------------------------------------------------------------\nNeya\n\nNeya was for the person who thought they could outplay anyone. Neya's kit offered her ways to bypass the typical rules of the game, at the cost of her own HP. This meant that if you were methodical, you could outplay someone or make a mistake and be their dinner. \n\nNeya's ability granted her the option to bypass the cooldown of her dimension swap, at the cost of health relative to % of time remaining."
                                },
                                {
                                    "type": "video",
                                    "url": "https://youtu.be/pnuwA0iMHVE",
                                    "caption": "Neya Ability Demo"
                                },
                                {
                                    "type": "text",
                                    "body": "Neya's ultimate was the ability to cloak herself. Note that this didn't stop her sounds; however it would be perceived by the enemies the same way her ability looked. This meant that you could make someone think you've changed dimensions by standing quite still. "
                                },
                                {
                                    "type": "video",
                                    "url": "https://youtu.be/kALBOS9FRGw",
                                    "caption": "Neya Ultimate Demo"
                                },
                                {
                                    "type": "text",
                                    "body": "--------------------------------------------------------------------------------------------------------------------------\nCleave\n\nCleave was designed for the person who may not believe in their ability to take a one-on-one, but has the analytical brain to scope out an area, to provide intel, and to help their team by arriving at the right time to provide support. \n\nCleave's ability created a copy of himself that could run around scoping areas out. However, this came at the risk of his main body being stationary. For the first few seconds of the drone, Cleave would be invisible before becoming revealed. At the end of the drone, he would regain control. "
                                },
                                {
                                    "type": "video",
                                    "url": "https://youtu.be/f_8HF2CEwM8",
                                    "caption": "Cleave Ability Demo"
                                },
                                {
                                    "type": "text",
                                    "body": "Cleave's ultimate was quite similar to his ability. He could mix it around which one he chose; however, he would have to commit. Using his ultimate would send out a drone; however, at the end of it, he would be transported to wherever the drone's position ended. This meant players needed to be cautious around his drone, as it could be simply for intel gathering or for rotation."
                                },
                                {
                                    "type": "video",
                                    "url": "https://youtu.be/YiXBE5G63ug",
                                    "caption": "Cleave Ultimate Demo"
                                },
                                {
                                    "type": "text",
                                    "body": "--------------------------------------------------------------------------------------------------------------------------\nNole\n\nNole was for the person who wanted to take every fight. They could power through and wanted to be the lead of their team. Nole wasn't exceptionally good in any specific fight, but was designed so that they had a chance in any fight. The skill of the player was what allowed Nole to be a dominant force. \n\nNole's ability was to shift between dimensions and become impervious for a short duration, with a slight buff to movement speed. "
                                },
                                {
                                    "type": "video",
                                    "url": "https://youtu.be/QSKBu4mnQG4",
                                    "caption": "Nole Ability Demo"
                                },
                                {
                                    "type": "text",
                                    "body": "Nole's ability was to become dimension agnostic, allowing for the shifting freely between dimensions, without being able to take damage, allowing for the free rotation anywhere. "
                                },
                                {
                                    "type": "video",
                                    "url": "https://youtu.be/CJAmMwv7cVM",
                                    "caption": "Nole Ultimate Demo"
                                }
                            ]
                        },
                        {
                            "title": "They Failed but Were Reborn",
                            "blocks": [
                                {
                                    "type": "text",
                                    "body": "Throughout the game's playtesting phases, complaints about characters began to arise.\n\nWhen a complaint would arise, some of the questions that we'd ask are:\n- Is this someone who doesn't like the character's goal?\n- Is this an issue or a design choice?\n- Is this an issue with the Numbers or the Concept\n\nWhile some issues would boil down to tuning within their numbers, others were issues with the design of the character, and a lot of characters fell for the same issue.\n\nTheir Ultimates were just their Abilities with a boost.\n\nThis could be seen as normal; however, I believe it is a problem. An ultimate isn't just a supercharged ability, but rather the embodiment of the character fantasy, supercharged. For example: Reinhardt's Ultimate isn't a bigger shield; it's the embodiment of a strong man \"Bringing The Hammer Down,\" causing those in his wake to come crashing down. Sova's Ultimate is closer to a supercharged shock dart; however, it's entirely different in its play and counterplay."
                                },
                                {
                                    "type": "text",
                                    "body": "When going into the redesigns, it was important to ask for player feedback. While they may not help with finding the exact solution, they are often great at identifying a problem. \n\nA new philosophy was devised for designing characters and their kits.\n1. Supercharging isn't an issue; however, it must be because the player used their PASSIVE in tandem with their Ability\n2. Ultimates are not just what the character already does but more. Rather, they are the embodiment of the action that the character's fantasy would take when the chips are down.\n3. The weapons characters use will be tied to the character, to better facilitate this direction.\n\nThe following are redesigned concepts of the character's kits and abilities. \n--------------------------------------------------------------------------------------------------------------------------"
                                },
                                {
                                    "type": "text",
                                    "body": "[Ghant]: SMG-Like, Short-Range Hit-and-Run\n\nFantasy: A player who wants speed, movement, and the fight to never stop. A Ghant player would want to be able to pick up the kit and fight. \n\nPassive: Numb: In a state of constant over-activity, Ghant doesn’t experience fatigue from jumping or sliding.\nAbility: Adrenaline: Adrenaline spikes, and Ghant’s movement speed, fire rate, and reload speed follow suit\nUltimate: Overdose: Grants Ghant the ability to swap between dimensions limitlessly and freely, as he is no longer grounded in reality. "
                                },
                                {
                                    "type": "text",
                                    "body": "[Allele]: Weak AR\n\nFantasy: Control over CC, whether dishing it out or receiving it. This player wants to manipulate the position of others and have control of the battlefield by manipulating the position of others.\n\nPassive: Dimensional Redirect: Any forced teleportation where Allele would be teleported by someone else; Allele will be instead moved to her pocket dimension (Requires being recharged)\nAbility: Collapse: Redirect a portal towards the pocket dimension however, the duration you can stay is severely diminished compared to the Ultimate\nUltimate: Pocket Dimension: Rapidly expanding outward; if touched on that plane of reality, be pulled into a dimension where their team has a buff lockout and a longer duration stay before being forced out."
                                },
                                {
                                    "type": "text",
                                    "body": "[Nole]: A charge shot/windup. Causes quick damage by landing the shot, but is punished in a continuous environment. \n\nFantasy: This player wishes to use their knowledge of timing, positioning, pathing, and cooldowns to create the best scenario for them to win. This player would thrive when getting the drop on someone.\n\nPassive: Spectral Watcher: See people for two seconds after their teleport\nAbility: Shooting Gallery: Huntress places a tether that allows her to shoot the ghosts of other players within the radius of the tether. If the tether breaks, it pulls the Huntress into the dimension in which she tethered. She can break it manually; it can be broken by others, and if she leaves the area, it auto breaks (great tool if someone's chasing her).\nUltimate: Strike Zone: Place an object in world space, denoted by a sphere. Anyone in the other dimension who enters this sphere is ripped into Huntress' current dimension."
                                },
                                {
                                    "type": "text",
                                    "body": "[Huntress]: Semi-Auto: Ambush Quick Pick, not Spam (Ashe / Guardian)\n\nFantasy: This player wishes to simply target someone and take them out. They thrive in a chase and love to isolate a one-on-one. \n\nPassive: Hunter’s Retreat: Double jump\nAbility: Hijack: For a short duration after someone teleports away, walk up to and through their portals; slight damage buff. \nUltimate: Rift Gateway: Using your stored charge, quickly connect two points in both dimensions, creating a shortcut for you and your allies. "
                                },
                                {
                                    "type": "text",
                                    "body": "[Cleave]: Minigun with mad useless falloff\n\nFantasy: This is the type of player who wishes to hold the front line. This player wishes to be in the lead and help the team navigate and control the battlefield. \n\nPassive: Enhanced regeneration\nAbility: Butterfly Effect: Swap barriers and objects between dimensions to create opportunities, or prevent others from doing so.\nUltimate: Grandfather Paradox: Create a bubble of space-time preventing abilities and bullets alike from entering."
                                }
                            ]
                        }
                    ]
                },
                {
                    "title": "Designing The Maps",
                    "feature": "The Maps",
                    "pages": [
                        {
                            "title": "Designing the Maps: The Prototype",
                            "blocks": [
                                {
                                    "type": "text",
                                    "body": "The following is taken throughout the development of Displaced. Seen will be versions of the map \"Idona\". \n\nIdona originally was conceived as a map that used the traditional three-lane design, but vertically. Throughout its original concepting phase, we added elements such as elevators and created tunnels in order to facilitate the pathing of players. \n\nWe noted it was quite fun; however, there were key issues, especially in regard to the tunnels. They were long funnels that didn't have any way of breaking up line of sight. They did help players cross the point more easily; however, they fell into the trap of what Displaced was trying to avoid (one-sided chokes). \n\nAfter our first couple of prototypes internally, we produced Version 1 of the map (seen later)."
                                },
                                {
                                    "type": "image",
                                    "path": "assets/Displaced/Breakdown/breakdown_mubzocym92kd.png",
                                    "caption": "Top Down",
                                    "mode": "normal",
                                    "afterPath": "",
                                    "beforeLabel": "",
                                    "afterLabel": ""
                                },
                                {
                                    "type": "image",
                                    "path": "assets/Displaced/Breakdown/breakdown_mubz403i9bxp.png",
                                    "caption": "Looking at Point",
                                    "mode": "normal",
                                    "afterPath": "",
                                    "beforeLabel": "",
                                    "afterLabel": ""
                                },
                                {
                                    "type": "image",
                                    "path": "assets/Displaced/Breakdown/breakdown_mubz4crp5hyv.png",
                                    "caption": "One of the first prototypes",
                                    "mode": "normal",
                                    "afterPath": "",
                                    "beforeLabel": "",
                                    "afterLabel": ""
                                },
                                {
                                    "type": "image",
                                    "path": "assets/Displaced/Breakdown/breakdown_mubzoen3ucix.png",
                                    "caption": "Looking at Tunnel",
                                    "mode": "normal",
                                    "afterPath": "",
                                    "beforeLabel": "",
                                    "afterLabel": ""
                                }
                            ]
                        },
                        {
                            "title": "Designing the Maps: Version 1",
                            "blocks": [
                                {
                                    "type": "text",
                                    "body": "Displaced has always been a small project; however, that doesn't mean we want it sheltered. We've had the opportunity to put it in front of 50+ players ranging across all backgrounds. \n\nPlaytesting has always been a major helpful element that allows us to improve, as we are aware that we'll never be right the first time, but it's important to adapt to what's needed. \n\nIn Version 1, we stripped out the tunnel underneath. We felt this tunnel was not only not being used, but also created friction points on the exit tunnels, as the systems didn't let it feel expressive and create the moments we were targeting. It's one of the reasons we decided to create more open areas. Switching between two dimensions becomes null and void if players teleport, but remain in the same place that they were in previous versions; it simply ends up extending time to kill, without improving the experience. \n\nCommon complaints in this era unfortunately stemmed from the system creating pain points within the maps that made them the priority, and left the maps in limbo for a while.  One major map change was the removal of the elevator entirely. In concept, it sounded cool to have this trade-off for standing still to get high ground, but it resulted in a boring and stressful element that was not that rewarding. Alternative paths proved more valuable and were thus removed. \n\nI also had time to have Version 1 peer reviewed by another developer. This was some of the most extremely helpful feedback, as there were a lot of issues. \n- The area was extremely linear. Players only had one viable exit from their spawn, leading to a plethora of issues.\n- The back section felt irrelevant and was very locked down, preventing easy rotation and free flow.\n- The high ground that littered the sections on the south side, while having interesting skill elements, required too much cognitive load and was too inconsistent, with no cover. "
                                },
                                {
                                    "type": "image",
                                    "path": "assets/Displaced/Breakdown/breakdown_muc0w2mr8osl.png",
                                    "caption": "Top Down",
                                    "mode": "normal",
                                    "afterPath": "",
                                    "beforeLabel": "",
                                    "afterLabel": ""
                                },
                                {
                                    "type": "image",
                                    "path": "assets/Displaced/Breakdown/breakdown_mubzte0vjwvz.png",
                                    "caption": "From Heaven",
                                    "mode": "normal",
                                    "afterPath": "",
                                    "beforeLabel": "",
                                    "afterLabel": ""
                                },
                                {
                                    "type": "image",
                                    "path": "assets/Displaced/Breakdown/breakdown_mubzuyvyonn7.png",
                                    "caption": "Backside Facing Point",
                                    "mode": "normal",
                                    "afterPath": "",
                                    "beforeLabel": "",
                                    "afterLabel": ""
                                },
                                {
                                    "type": "image",
                                    "path": "assets/Displaced/Breakdown/breakdown_mubzvcpyr6t4.png",
                                    "caption": "Front of Spawn",
                                    "mode": "normal",
                                    "afterPath": "",
                                    "beforeLabel": "",
                                    "afterLabel": ""
                                },
                                {
                                    "type": "image",
                                    "path": "assets/Displaced/Breakdown/breakdown_muc00mt5ivrs.png",
                                    "caption": "Top Down Denoted",
                                    "mode": "normal",
                                    "afterPath": "",
                                    "beforeLabel": "",
                                    "afterLabel": ""
                                }
                            ]
                        },
                        {
                            "title": "Designing the Maps: Version 2",
                            "blocks": [
                                {
                                    "type": "text",
                                    "body": "This whole time, players could swap dimensions once, travel anywhere unpredictably, and were \"trading\" positions with other players. This led to a feeling that players would just miss someone when trying to hunt them down.\n\nTo solve these issues, we looked back at inspirations and similar titles. We noted a lot more freedom, in which the players had to move more than once. Players had a lot more freedom to make their way in and out of tight situations, and so we wanted to try that by allowing players multiple uses, but with more punishment for not having them. This created a new issue of players being all over the place.\n\nWe decided we could now add irregularities or items that are there in one dimension, but not in the other. When players only had one use, this could create a hard wall for the player that they couldn’t move past and were thus stuck waiting a long time before being able to proceed. However, now with two uses, we could better justify the scenarios in which you can better predict where someone might appear.\n\nThe introduction of irregularities dramatically improved the feeling of the core mechanic and allowed us to experiment to find the best combination of punishing those who swapped poorly while allowing thoughtful pathing. \n\nWe also improved the pathing from a player's spawn to the main point, reverting back to the more normalized three-lane design and focusing more on what elevated the game without trying to break the mold. "
                                },
                                {
                                    "type": "image",
                                    "path": "assets/Displaced/Breakdown/breakdown_muc0wclfec4y.png",
                                    "caption": "Prototyping New Version",
                                    "mode": "normal",
                                    "afterPath": "",
                                    "beforeLabel": "",
                                    "afterLabel": ""
                                },
                                {
                                    "type": "image",
                                    "path": "assets/Displaced/Breakdown/breakdown_muc09iadhxjc.png",
                                    "caption": "Exiting Spawn",
                                    "mode": "normal",
                                    "afterPath": "",
                                    "beforeLabel": "",
                                    "afterLabel": ""
                                },
                                {
                                    "type": "image",
                                    "path": "assets/Displaced/Breakdown/breakdown_muc09wk9w9ou.png",
                                    "caption": "From Heaven",
                                    "mode": "normal",
                                    "afterPath": "",
                                    "beforeLabel": "",
                                    "afterLabel": ""
                                },
                                {
                                    "type": "image",
                                    "path": "assets/Displaced/Breakdown/breakdown_muc09men7rs3.png",
                                    "caption": "Backside Facing Point",
                                    "mode": "normal",
                                    "afterPath": "",
                                    "beforeLabel": "",
                                    "afterLabel": ""
                                },
                                {
                                    "type": "image",
                                    "path": "assets/Displaced/Breakdown/breakdown_muc0aaczft1f.png",
                                    "caption": "Sitting In Mid",
                                    "mode": "normal",
                                    "afterPath": "",
                                    "beforeLabel": "",
                                    "afterLabel": ""
                                }
                            ]
                        },
                        {
                            "title": "Designing the Maps: Where We are Now",
                            "blocks": [
                                {
                                    "type": "text",
                                    "body": "Idona's map design has taken on many changes throughout its lifetime. \n\nTo say it won't see any more would be far from correct; however, with each iteration, it has allowed for continuous improvement in order to highlight the player experience that's the most entertaining rather than throwing mechanics everywhere. "
                                },
                                {
                                    "type": "image",
                                    "path": "assets/Displaced/Breakdown/breakdown_muc0yc00ege3.png",
                                    "caption": "Top Down",
                                    "mode": "normal",
                                    "afterPath": "",
                                    "beforeLabel": "",
                                    "afterLabel": ""
                                },
                                {
                                    "type": "image",
                                    "path": "assets/Displaced/Breakdown/breakdown_muc0c32xwcam.png",
                                    "caption": "Exiting Spawn",
                                    "mode": "normal",
                                    "afterPath": "",
                                    "beforeLabel": "",
                                    "afterLabel": ""
                                },
                                {
                                    "type": "image",
                                    "path": "assets/Displaced/Breakdown/breakdown_muc0c5gqtzmc.png",
                                    "caption": "Backside Facing Point",
                                    "mode": "normal",
                                    "afterPath": "",
                                    "beforeLabel": "",
                                    "afterLabel": ""
                                },
                                {
                                    "type": "image",
                                    "path": "assets/Displaced/Breakdown/breakdown_muc0ca6t3p9m.png",
                                    "caption": "Sitting In Mid",
                                    "mode": "normal",
                                    "afterPath": "",
                                    "beforeLabel": "",
                                    "afterLabel": ""
                                },
                                {
                                    "type": "image",
                                    "path": "assets/Displaced/Breakdown/breakdown_muc118yltu2a.png",
                                    "caption": "Facing Spawn and Tunnels",
                                    "mode": "normal",
                                    "afterPath": "",
                                    "beforeLabel": "",
                                    "afterLabel": ""
                                },
                                {
                                    "type": "image",
                                    "path": "assets/Displaced/Breakdown/breakdown_muc127963i2z.png",
                                    "caption": "Inside the New Tunnels",
                                    "mode": "normal",
                                    "afterPath": "",
                                    "beforeLabel": "",
                                    "afterLabel": ""
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        "mediaCaptions": {
            "image:assets/Displaced/displayPhoto_3.png": "Progression of the Map Design",
            "image:assets/Displaced/displayPhoto_2.png": "Dimensions Designed to Path the Player"
        },
        "mediaOrder": [],
        "mediaCompare": {
            "image:assets/Displaced/displayPhoto_3.png": {
                "mode": "slider",
                "afterPath": "assets/Displaced/Compare/compare_mud272xorzwe.png",
                "beforeLabel": "Idona Version 1",
                "afterLabel": "Idona Version 2"
            },
            "image:assets/Displaced/displayPhoto_2.png": {
                "mode": "slider",
                "afterPath": "assets/Displaced/Compare/compare_mud2ck8tukvm.png",
                "beforeLabel": "Dimension A",
                "afterLabel": "Dimension B"
            }
        }
    }
];

const about = {
    "bullets": [
        "Bachelors - Management Information Systems",
        "Half a decade of game development experience.",
        "First Person and Multiplayer Specialist"
    ],
    "resumePath": "assets/Jason Firth Resume.pdf",
    "headshot": "assets/JasonHeadshot.png",
    "links": [
        {
            "label": "Itch.Io",
            "url": "https://dev-stynt.itch.io/"
        },
        {
            "label": "LinkedIn",
            "url": "https://www.linkedin.com/in/jason-firth-b76a7418a/"
        }
    ]
};

const experience = [
    {
        "id": "benthic-games",
        "dateRange": "May 2025 - Present",
        "title": "Contract Developer",
        "organization": "Benthic Studio",
        "tech": [
            "Unity",
            "Substance Painter",
            "Steamworks SDK",
            "C#",
            "Blender",
            "FL Studio",
            "Wwise"
        ],
        "description": "Providing adaptable solutions to a variety of problems. From game development, custom software, media content, and webpages.",
        "bullets": [
            "Redesigned the progression for a serious games client, validated through playtesting and player sentiment",
            "Diagnosed a churn point for a client through playtest observation and analytical review, then redesigned the flow, reducing early quit rates",
            "Identified and fixed issues in a client's web build, improving the players’ experience"
        ]
    },
    {
        "id": "ctk-livestream",
        "dateRange": "Sep 2021 - Present",
        "title": "Live Stream Technician ",
        "organization": "CTK",
        "tech": [
            "Python"
        ],
        "description": "Revamped and maintained live streaming systems in live production environments.",
        "bullets": [
            "Problem solved technical difficulties in swift and creative ways to avoid downtime",
            "Problem-solved technical difficulties swiftly to avoid downtime",
            "Coordinated teams and communicated effectively for delivery"
        ]
    },
    {
        "id": "fast-enterprises",
        "dateRange": "Jun 2024 - Aug 2024",
        "title": "Implementation Consultant Intern",
        "organization": "Fast Enterprises, LLC",
        "tech": [
            "C#"
        ],
        "description": "As a designer positioned perfectly with my understanding of design, systems, and business, I can target a pain point affecting players, propose a solution, and prototype it's effectiveness with the ability to restart if and when needed. ",
        "bullets": [
            "Conveying Technical processes and information to a range of non-technical users. ",
            "Designed demonstrations on new systems and workflows for clients with a varying range of technical expertise"
        ]
    }
];

const CONFIG = {
    "imageTimeout": 500,
    "lazyLoadingThreshold": 0.1,
    "enableLazyLoading": true,
    "maxConcurrentLoads": 3,
    "retryAttempts": 1,
    "preloadCriticalImages": true,
    "enableImageCache": true
};

