// AUTO-GENERATED by admin tool. Hand edits will be overwritten.
// Source of truth: portfolio admin at http://localhost:3000/admin

const techStack = [
    {
        "name": "Unity",
        "icon": "fab fa-unity",
        "projects": [
            "from-the-ashes",
            "strictly-human",
            "mr-bubbles",
            "displaced"
        ]
    },
    {
        "name": "Substance Painter",
        "icon": "assets/icons/SubstancePainterGray.png",
        "projects": [
            "mr-bubbles",
            "displaced"
        ]
    },
    {
        "name": "Steamworks SDK",
        "icon": "fab fa-steam",
        "projects": [
            "displaced"
        ]
    },
    {
        "name": "Git",
        "icon": "fab fa-git-alt",
        "projects": [
            "mr-bubbles",
            "displaced"
        ]
    },
    {
        "name": "Python",
        "icon": "fab fa-python",
        "projects": []
    },
    {
        "name": "C#",
        "icon": "assets/icons/csharpGray.png",
        "projects": [
            "from-the-ashes",
            "strictly-human",
            "mr-bubbles",
            "displaced"
        ]
    },
    {
        "name": "Blender",
        "icon": "assets/icons/blender.ico",
        "projects": [
            "mr-bubbles",
            "displaced"
        ]
    },
    {
        "name": "FL Studio",
        "icon": "assets/icons/FLGray.png",
        "projects": [
            "strictly-human",
            "mr-bubbles"
        ]
    },
    {
        "name": "Wwise",
        "icon": "assets/icons/wwiseGray.png",
        "projects": [
            "displaced"
        ]
    }
];

const imageInventory = {
    "displaced": {
        "thumbnail": "assets/Displaced/thumbnailPhoto.png",
        "displayImages": [
            "assets/Displaced/displayPhoto_1.png",
            "assets/Displaced/displayPhoto_2.png",
            "assets/Displaced/displayPhoto_3.png",
            "assets/Displaced/displayPhoto_4.png"
        ]
    },
    "mr-bubbles": {
        "thumbnail": "assets/MrBubbles/thumbnailPhoto.png",
        "displayImages": [
            "assets/MrBubbles/displayPhoto_1.png",
            "assets/MrBubbles/displayPhoto_2.png",
            "assets/MrBubbles/displayPhoto_3.png"
        ]
    },
    "from-the-ashes": {
        "thumbnail": "assets/FromTheAshes/thumbnailPhoto.png",
        "displayImages": [
            "assets/FromTheAshes/displayPhoto_1.png",
            "assets/FromTheAshes/displayPhoto_2.png",
            "assets/FromTheAshes/displayPhoto_3.png"
        ]
    },
    "strictly-human": {
        "thumbnail": "assets/StrictlyHumanAffair/thumbnailPhoto.jpeg",
        "displayImages": [
            "assets/StrictlyHumanAffair/displayPhoto_1.jpg",
            "assets/StrictlyHumanAffair/displayPhoto_2.jpg",
            "assets/StrictlyHumanAffair/displayPhoto_3.jpg",
            "assets/StrictlyHumanAffair/displayPhoto_4.jpg"
        ]
    }
};

const projects = [
    {
        "id": "from-the-ashes",
        "assetFolder": "FromTheAshes",
        "type": "gamejam",
        "duration": "1 Week",
        "youtubeUrls": [],
        "title": "From The Ashes",
        "description": "A Multiplayer Horror, scour the area, and return safely.",
        "image": "fas fa-gamepad",
        "thumbnailUrl": null,
        "tech": [
            "Unity",
            "C#"
        ],
        "featured": false,
        "detailsEnabled": false,
        "media": [],
        "overview": {
            "description": "A new type of creature, known as Phons, is overruning the world. They are spreading wildly. The military sends troops to ground zero to collect a sample.\n\nEach player must enter ground zero. Find the sample, and get out. However, it won't be that simple. When encountering their foe, they must be careful, as it doesn't die; it adapts. \n\nThe Phon is designed with the ability not to die, but rather to adapt to the method by which it was hurt. Knock it over for a short duration before it stands up with better tools in its arsenal. To handle melee weapons, it will develop ranged weapons, and to meet ranged weapons with armor.\n\n",
            "features": [
                "CO-OP",
                "First Person Combat"
            ],
            "platforms": [
                "Windows",
                "Mac",
                "Linux"
            ],
            "status": "Released",
            "role": "Lead Dev",
            "storeUrl": "https://dev-stynt.itch.io/from-the-ashes-they-rise"
        },
        "details": {
            "challenges": [],
            "solutions": [],
            "lessons": [],
            "pages": []
        },
        "mediaCaptions": {}
    },
    {
        "id": "strictly-human",
        "assetFolder": "StrictlyHumanAffair",
        "type": "gamejam",
        "duration": "72 Hours",
        "youtubeUrls": [],
        "title": "A Strictly Human Affair",
        "description": "A first person, social puzzle game. Explore the train, collect items, and learn the secrets each passenger holds. ",
        "image": "fas fa-gamepad",
        "thumbnailUrl": null,
        "tech": [
            "Unity",
            "C#",
            "FL Studio"
        ],
        "featured": false,
        "detailsEnabled": false,
        "media": [],
        "overview": {
            "description": "When the train conductor is found brutally murdered, Sheriff Horace; trapped in a rolling prison alongside six other passengers, must reveal the monstrous killer from behind their mask.",
            "features": [
                "Narrative"
            ],
            "platforms": [
                "Windows",
                "Linux",
                "Mac"
            ],
            "status": "Released",
            "role": "Developer",
            "storeUrl": "https://ratth3cat.itch.io/a-strictly-human-affair"
        },
        "details": {
            "challenges": [],
            "solutions": [],
            "lessons": [],
            "pages": []
        },
        "mediaCaptions": {}
    },
    {
        "id": "mr-bubbles",
        "assetFolder": "MrBubbles",
        "type": "gamejam",
        "duration": "72 Hours",
        "youtubeUrls": [
            "https://youtu.be/qXJDq9WIIj8"
        ],
        "detailsEnabled": false,
        "title": "Mr. Bubbles Car Wash",
        "description": "A charming cleaning simulation game where players manage a car wash business with whimsical characters.",
        "image": "fas fa-car",
        "thumbnailUrl": null,
        "tech": [
            "Unity",
            "C#",
            "Substance Painter",
            "Git",
            "Blender",
            "FL Studio"
        ],
        "featured": true,
        "media": [],
        "overview": {
            "description": "Mr. Bubbles Car Wash combines business simulation with subtle character-driven storytelling.",
            "features": [
                "Business management and progression systems",
                "Dynamic Clientele",
                "Detailed car washing mini-games",
                "Custom 3D environments"
            ],
            "platforms": [
                "Windows",
                "Itch.io"
            ],
            "status": "Released",
            "role": "Programmer, Sound Artist",
            "storeUrl": "https://qrypt.itch.io/mr-bubbles-car-salon"
        },
        "details": {
            "challenges": [
                "Creating an immersive dirt decal system",
                "Creating engaging characters within a simple business premise",
                "Designing satisfying progression systems that encourage long-term play",
                "The implementation of systems designed. Code Was ready, yet implementation takes time"
            ],
            "solutions": [
                "A Render Based decal Stamp and collision detection to spawn and clean dirt",
                "Used Blender and Substance Painter to create basic car-wash environment",
                "Designed a procedural and modular dirt generation and cleaning system"
            ],
            "lessons": [
                "Don't wait until the final moment to think about how you will create a tutorial",
                "Feedback is critical, but a problem has multiple solutions",
                "Ensure Polish on elements possessed rather than attempting to produce rushed concepts."
            ],
            "pages": []
        },
        "mediaOrder": [
            "image:assets/MrBubbles/displayPhoto_1.png",
            "youtube:qXJDq9WIIj8",
            "image:assets/MrBubbles/displayPhoto_2.png",
            "image:assets/MrBubbles/displayPhoto_3.png"
        ],
        "mediaCaptions": {}
    },
    {
        "id": "displaced",
        "assetFolder": "Displaced",
        "type": "project",
        "youtubeUrls": [],
        "detailsEnabled": true,
        "title": "Displaced",
        "description": "A First Person Multiplayer FPS, fight across two dimensions to conquer reality, and survive the oncoming apocalypse.",
        "image": "fas fa-gamepad",
        "thumbnailUrl": null,
        "tech": [
            "Unity",
            "C#",
            "Substance Painter",
            "Steamworks SDK",
            "Git",
            "Blender",
            "Wwise"
        ],
        "featured": false,
        "media": [],
        "overview": {
            "description": "Displaced takes place across two realities, fighting for control. Players must switch between these realities mid-fight to obtain the best positioning advantage. \n\nDisplaced offers a unique team shooter dynamic where players have the ability to better navigate the map. The ability to swap dimensions prevents the feeling of getting fully stuck in tight, narrow areas or getting camped. ",
            "features": [
                "Multiplayer, First Person Shooter",
                "Team Based, Hero Shooter",
                "Two Dimensions - One Fight",
                "Spatial audio design using Wwise"
            ],
            "platforms": [
                "PC",
                "Steam"
            ],
            "status": "In Development",
            "role": "Lead Developer",
            "storeUrl": null
        },
        "details": {
            "challenges": [],
            "solutions": [],
            "lessons": [],
            "pages": [
                {
                    "title": "Designing the Maps: The Prototype",
                    "body": "The following is taken throughout the development of Displaced. Seen will be versions of the map \"Idona\". \n\nIdona originally was conceived as a map that used the traditional three-lane design, but vertically. Throughout its original concepting phase, we added elements such as elevators and created tunnels in order to facilitate the pathing of players. \n\nWe noted it was quite fun; however, there were key issues, especially in regard to the tunnels. They were long funnels that didn't have any way of breaking up line of sight. They did help players cross the point more easily; however, they fell into the trap of what Displaced was trying to avoid (one-sided chokes). \n\nAfter our first couple of prototypes internally, we produced Version 1 of the map (seen later).",
                    "images": [
                        {
                            "path": "assets/Displaced/Breakdown/breakdown_mubzocym92kd.png",
                            "caption": "Top Down"
                        },
                        {
                            "path": "assets/Displaced/Breakdown/breakdown_mubz403i9bxp.png",
                            "caption": "Looking at Point"
                        },
                        {
                            "path": "assets/Displaced/Breakdown/breakdown_mubz4crp5hyv.png",
                            "caption": "One of the first prototypes"
                        },
                        {
                            "path": "assets/Displaced/Breakdown/breakdown_mubzoen3ucix.png",
                            "caption": "Looking at Tunnel"
                        }
                    ]
                },
                {
                    "title": "Designing the Maps: Version 1",
                    "body": "Displaced has always been a small project; however, that doesn't mean we want it sheltered. We've had the opportunity to put it in front of 50+ players ranging across all backgrounds. \n\nPlaytesting has always been a major helpful element that allows us to improve, as we are aware that we'll never be right the first time, but it's important to adapt to what's needed. \n\nIn Version 1, we stripped out the tunnel underneath. We felt this tunnel was not only not being used, but also created friction points on the exit tunnels, as the systems didn't let it feel expressive and create the moments we were targeting. It's one of the reasons we decided to create more open areas. Switching between two dimensions becomes null and void if players teleport, but remain in the same place that they were in previous versions; it simply ends up extending time to kill, without improving the experience. \n\nCommon complaints in this era unfortunately stemmed from the system creating pain points within the maps that made them the priority, and left the maps in limbo for a while.  One major map change was the removal of the elevator entirely. In concept, it sounded cool to have this trade-off for standing still to get high ground, but it resulted in a boring and stressful element that was not that rewarding. Alternative paths proved more valuable and were thus removed. \n\nI also had time to have Version 1 peer reviewed by another developer. This was some of the most extremely helpful feedback, as there were a lot of issues. \n- The area was extremely linear. Players only had one viable exit from their spawn, leading to a plethora of issues.\n- The back section felt irrelevant and was very locked down, preventing easy rotation and free flow.\n- The high ground that littered the sections on the south side, while having interesting skill elements, required too much cognitive load and was too inconsistent, with no cover. ",
                    "images": [
                        {
                            "path": "assets/Displaced/Breakdown/breakdown_muc0w2mr8osl.png",
                            "caption": "Top Down"
                        },
                        {
                            "path": "assets/Displaced/Breakdown/breakdown_mubzte0vjwvz.png",
                            "caption": "From Heaven"
                        },
                        {
                            "path": "assets/Displaced/Breakdown/breakdown_mubzuyvyonn7.png",
                            "caption": "Backside Facing Point"
                        },
                        {
                            "path": "assets/Displaced/Breakdown/breakdown_mubzvcpyr6t4.png",
                            "caption": "Front of Spawn"
                        },
                        {
                            "path": "assets/Displaced/Breakdown/breakdown_muc00mt5ivrs.png",
                            "caption": "Top Down Denoted"
                        }
                    ]
                },
                {
                    "title": "Designing the Maps: Version 2",
                    "body": "This whole time, players could swap dimensions once, travel anywhere unpredictably, and were \"trading\" positions with other players. This led to a feeling that players would just miss someone when trying to hunt them down.\n\nTo solve these issues, we looked back at inspirations and similar titles. We noted a lot more freedom, in which the players had to move more than once. Players had a lot more freedom to make their way in and out of tight situations, and so we wanted to try that by allowing players multiple uses, but with more punishment for not having them. This created a new issue of players being all over the place.\n\nWe decided we could now add irregularities or items that are there in one dimension, but not in the other. When players only had one use, this could create a hard wall for the player that they couldn’t move past and were thus stuck waiting a long time before being able to proceed. However, now with two uses, we could better justify the scenarios in which you can better predict where someone might appear.\n\nThe introduction of irregularities dramatically improved the feeling of the core mechanic and allowed us to experiment to find the best combination of punishing those who swapped poorly while allowing thoughtful pathing. \n\nWe also improved the pathing from a player's spawn to the main point, reverting back to the more normalized three-lane design and focusing more on what elevated the game without trying to break the mold. ",
                    "images": [
                        {
                            "path": "assets/Displaced/Breakdown/breakdown_muc0wclfec4y.png",
                            "caption": "Prototyping New Version"
                        },
                        {
                            "path": "assets/Displaced/Breakdown/breakdown_muc09iadhxjc.png",
                            "caption": "Exiting Spawn"
                        },
                        {
                            "path": "assets/Displaced/Breakdown/breakdown_muc09wk9w9ou.png",
                            "caption": "From Heaven"
                        },
                        {
                            "path": "assets/Displaced/Breakdown/breakdown_muc09men7rs3.png",
                            "caption": "Backside Facing Point"
                        },
                        {
                            "path": "assets/Displaced/Breakdown/breakdown_muc0aaczft1f.png",
                            "caption": "Sitting In Mid"
                        }
                    ]
                },
                {
                    "title": "Designing the Maps: Where We are Now",
                    "body": "Idona's map design has taken on many changes throughout its lifetime. \n\nTo say it won't see any more would be far from correct; however, with each iteration, it has allowed for continuous improvement in order to highlight the player experience that's the most entertaining rather than throwing mechanics everywhere. ",
                    "images": [
                        {
                            "path": "assets/Displaced/Breakdown/breakdown_muc0yc00ege3.png",
                            "caption": "Top Down"
                        },
                        {
                            "path": "assets/Displaced/Breakdown/breakdown_muc0c32xwcam.png",
                            "caption": "Exiting Spawn"
                        },
                        {
                            "path": "assets/Displaced/Breakdown/breakdown_muc0c5gqtzmc.png",
                            "caption": "Backside Facing Point"
                        },
                        {
                            "path": "assets/Displaced/Breakdown/breakdown_muc0ca6t3p9m.png",
                            "caption": "Sitting In Mid"
                        },
                        {
                            "path": "assets/Displaced/Breakdown/breakdown_muc118yltu2a.png",
                            "caption": "Facing Spawn and Tunnels"
                        },
                        {
                            "path": "assets/Displaced/Breakdown/breakdown_muc127963i2z.png",
                            "caption": "Inside the New Tunnels"
                        }
                    ]
                }
            ]
        },
        "mediaCaptions": {
            "image:assets/Displaced/displayPhoto_2.png": "Backside in Version 1",
            "image:assets/Displaced/displayPhoto_3.png": "Backside in Version 2",
            "image:assets/Displaced/displayPhoto_4.png": "Backside in Version 3"
        },
        "mediaOrder": []
    }
];

const about = {
    "bullets": [
        "Bachelors - Management Information Systems",
        "Half a decade of game development experience.",
        "First Person and Multiplayer Specialist"
    ],
    "resumePath": "assets/Jason Firth Resume.pdf",
    "headshot": "assets/JasonHeadshot.png",
    "links": [
        {
            "label": "Itch.Io",
            "url": "https://dev-stynt.itch.io/"
        },
        {
            "label": "LinkedIn",
            "url": "https://www.linkedin.com/in/jason-firth-b76a7418a/"
        }
    ]
};

const experience = [
    {
        "id": "benthic-games",
        "dateRange": "May 2025 - Present",
        "title": "Contract Developer",
        "organization": "Benthic Studio",
        "tech": [
            "Unity",
            "Substance Painter",
            "Steamworks SDK",
            "C#",
            "Blender",
            "FL Studio",
            "Wwise"
        ],
        "description": "Providing adaptable solutions to a variety of problems. From game development, custom software, media content, and webpages.",
        "bullets": [
            "Redesigned the progression for a serious games client, validated through playtesting and player sentiment",
            "Diagnosed a churn point for a client through playtest observation and analytical review, then redesigned the flow, reducing early quit rates",
            "Identified and fixed issues in a client's web build, improving the players’ experience"
        ]
    },
    {
        "id": "ctk-livestream",
        "dateRange": "Sep 2021 - Present",
        "title": "Live Stream Technician ",
        "organization": "CTK",
        "tech": [
            "Python"
        ],
        "description": "Revamped and maintained live streaming systems in live production environments.",
        "bullets": [
            "Problem solved technical difficulties in swift and creative ways to avoid downtime",
            "Problem-solved technical difficulties swiftly to avoid downtime",
            "Coordinated teams and communicated effectively for delivery"
        ]
    },
    {
        "id": "fast-enterprises",
        "dateRange": "Jun 2024 - Aug 2024",
        "title": "Implementation Consultant Intern",
        "organization": "Fast Enterprises, LLC",
        "tech": [
            "C#"
        ],
        "description": "As a designer positioned perfectly with my understanding of design, systems, and business, I can target a pain point affecting players, propose a solution, and prototype it's effectiveness with the ability to restart if and when needed. ",
        "bullets": [
            "Conveying Technical processes and information to a range of non-technical users. ",
            "Designed demonstrations on new systems and workflows for clients with a varying range of technical expertise"
        ]
    }
];

const CONFIG = {
    "imageTimeout": 500,
    "lazyLoadingThreshold": 0.1,
    "enableLazyLoading": true,
    "maxConcurrentLoads": 3,
    "retryAttempts": 1,
    "preloadCriticalImages": true,
    "enableImageCache": true
};

