// AUTO-GENERATED by admin tool. Hand edits will be overwritten.
// Source of truth: portfolio admin at http://localhost:3000/admin

const techStack = [
    {
        "name": "Unity",
        "icon": "fab fa-unity",
        "projects": [
            "mr-bubbles",
            "strictly-human",
            "from-the-ashes",
            "displaced"
        ]
    },
    {
        "name": "Substance Painter",
        "icon": "assets/icons/SubstancePainterGray.png",
        "projects": [
            "mr-bubbles",
            "displaced"
        ]
    },
    {
        "name": "Steamworks SDK",
        "icon": "fab fa-steam",
        "projects": [
            "displaced"
        ]
    },
    {
        "name": "Git",
        "icon": "fab fa-git-alt",
        "projects": [
            "mr-bubbles",
            "displaced"
        ]
    },
    {
        "name": "Python",
        "icon": "fab fa-python",
        "projects": []
    },
    {
        "name": "C#",
        "icon": "assets/icons/csharpGray.png",
        "projects": [
            "mr-bubbles",
            "strictly-human",
            "from-the-ashes",
            "displaced"
        ]
    },
    {
        "name": "Blender",
        "icon": "assets/icons/blender.ico",
        "projects": [
            "mr-bubbles",
            "displaced"
        ]
    },
    {
        "name": "FL Studio",
        "icon": "assets/icons/FLGray.png",
        "projects": [
            "mr-bubbles",
            "strictly-human"
        ]
    },
    {
        "name": "Wwise",
        "icon": "assets/icons/wwiseGray.png",
        "projects": [
            "displaced"
        ]
    }
];

const imageInventory = {
    "displaced": {
        "thumbnail": "assets/Displaced/thumbnailPhoto.png",
        "displayImages": [
            "assets/Displaced/displayPhoto_1.png",
            "assets/Displaced/displayPhoto_2.png",
            "assets/Displaced/displayPhoto_3.png",
            "assets/Displaced/displayPhoto_4.png"
        ],
        "comparisonImages": [
            "assets/Displaced/Comparison/comparisonPhoto_1.jpg",
            "assets/Displaced/Comparison/comparisonPhoto_2.jpg",
            "assets/Displaced/Comparison/comparisonPhoto_3.jpg"
        ]
    },
    "mr-bubbles": {
        "thumbnail": "assets/MrBubbles/thumbnailPhoto.png",
        "displayImages": [
            "assets/MrBubbles/displayPhoto_1.png",
            "assets/MrBubbles/displayPhoto_2.png",
            "assets/MrBubbles/displayPhoto_3.png"
        ],
        "comparisonImages": []
    },
    "from-the-ashes": {
        "thumbnail": "assets/FromTheAshes/thumbnailPhoto.png",
        "displayImages": [
            "assets/FromTheAshes/displayPhoto_1.png",
            "assets/FromTheAshes/displayPhoto_2.png",
            "assets/FromTheAshes/displayPhoto_3.png"
        ],
        "comparisonImages": []
    },
    "strictly-human": {
        "thumbnail": "assets/StrictlyHumanAffair/thumbnailPhoto.jpeg",
        "displayImages": [
            "assets/StrictlyHumanAffair/displayPhoto_1.jpg",
            "assets/StrictlyHumanAffair/displayPhoto_2.jpg",
            "assets/StrictlyHumanAffair/displayPhoto_3.jpg",
            "assets/StrictlyHumanAffair/displayPhoto_4.jpg"
        ],
        "comparisonImages": []
    }
};

const projects = [
    {
        "id": "mr-bubbles",
        "assetFolder": "MrBubbles",
        "type": "gamejam",
        "duration": "72 Hours",
        "youtubeUrls": [
            "https://youtu.be/qXJDq9WIIj8"
        ],
        "detailsEnabled": false,
        "title": "Mr. Bubbles Car Wash",
        "description": "A charming cleaning simulation game where players manage a car wash business with whimsical characters.",
        "image": "fas fa-car",
        "thumbnailUrl": null,
        "tech": [
            "Unity",
            "C#",
            "Substance Painter",
            "Git",
            "Blender",
            "FL Studio"
        ],
        "featured": true,
        "media": [],
        "overview": {
            "description": "Mr. Bubbles Car Wash combines business simulation with subtle character-driven storytelling.",
            "features": [
                "Business management and progression systems",
                "Dynamic Clientele",
                "Detailed car washing mini-games",
                "Custom 3D environments"
            ],
            "platforms": [
                "Windows",
                "Itch.io"
            ],
            "status": "Released",
            "role": "Programmer, Sound Artist",
            "storeUrl": "https://qrypt.itch.io/mr-bubbles-car-salon"
        },
        "details": {
            "challenges": [
                "Creating an immersive dirt decal system",
                "Creating engaging characters within a simple business premise",
                "Designing satisfying progression systems that encourage long-term play",
                "The implementation of systems designed. Code Was ready, yet implementation takes time"
            ],
            "solutions": [
                "A Render Based decal Stamp and collision detection to spawn and clean dirt",
                "Used Blender and Substance Painter to create basic car-wash environment",
                "Designed a procedural and modular dirt generation and cleaning system"
            ],
            "lessons": [
                "Don't wait until the final moment to think about how you will create a tutorial",
                "Feedback is critical, but a problem has multiple solutions",
                "Ensure Polish on elements possessed rather than attempting to produce rushed concepts."
            ],
            "comparison": {
                "title": "Short Term vs Long Term Project Length",
                "items": [
                    {
                        "name": "Mr. Bubbles",
                        "image": "fas fa-circle"
                    },
                    {
                        "name": "Traditional Sim",
                        "image": "fas fa-circle"
                    }
                ],
                "analysis": {
                    "ourApproach": {
                        "title": "Short Term Positives",
                        "description": "Mr. Bubbles Code was Created with longevity in mind, how did this positively affect the short term?",
                        "whatWorked": [
                            "Easy creation of multiple characters",
                            "Gameplay is performant",
                            "First variation of dirt was easy to implement",
                            "Git version control enabled collaborative audio and code development"
                        ]
                    },
                    "traditionalApproach": {
                        "title": "Short Term Negatives",
                        "description": "Because it was a short term game, not a long term game, what negatives did this have?",
                        "whatDidntWork": [
                            "Further progression of dirt / dirt types was designed, not implemented",
                            "Further item progression and tools required to clean was designed, not implemented",
                            "Elements that WERE implemented, were not as visually polished",
                            "Buggy math calculations",
                            "Lack of settings integrations"
                        ]
                    }
                },
                "media": []
            }
        },
        "mediaOrder": [
            "image:assets/MrBubbles/displayPhoto_1.png",
            "youtube:qXJDq9WIIj8",
            "image:assets/MrBubbles/displayPhoto_2.png",
            "image:assets/MrBubbles/displayPhoto_3.png"
        ]
    },
    {
        "id": "strictly-human",
        "assetFolder": "StrictlyHumanAffair",
        "type": "gamejam",
        "duration": "72 Hours",
        "youtubeUrls": [],
        "title": "A Strictly Human Affair",
        "description": "A first person, social puzzle game. Explore the train, collect items, and learn the secrets each passenger holds. ",
        "image": "fas fa-gamepad",
        "thumbnailUrl": null,
        "tech": [
            "Unity",
            "C#",
            "FL Studio"
        ],
        "featured": false,
        "detailsEnabled": false,
        "media": [],
        "overview": {
            "description": "When the train conductor is found brutally murdered, Sheriff Horace; trapped in a rolling prison alongside six other passengers, must reveal the monstrous killer from behind their mask.",
            "features": [
                "Narrative"
            ],
            "platforms": [
                "Windows",
                "Linux",
                "Mac"
            ],
            "status": "Released",
            "role": "Developer",
            "storeUrl": "https://ratth3cat.itch.io/a-strictly-human-affair"
        },
        "details": {
            "challenges": [],
            "solutions": [],
            "lessons": [],
            "comparison": {
                "title": "",
                "items": [
                    {
                        "name": "",
                        "image": "fas fa-circle"
                    },
                    {
                        "name": "",
                        "image": "fas fa-circle"
                    }
                ],
                "analysis": {
                    "ourApproach": {
                        "title": "",
                        "description": "",
                        "whatWorked": []
                    },
                    "traditionalApproach": {
                        "title": "",
                        "description": "",
                        "whatDidntWork": []
                    }
                },
                "media": []
            }
        }
    },
    {
        "id": "from-the-ashes",
        "assetFolder": "FromTheAshes",
        "type": "gamejam",
        "duration": "1 Week",
        "youtubeUrls": [],
        "title": "From The Ashes",
        "description": "A Multiplayer Horror, scour the area, and return safely.",
        "image": "fas fa-gamepad",
        "thumbnailUrl": null,
        "tech": [
            "Unity",
            "C#"
        ],
        "featured": false,
        "detailsEnabled": false,
        "media": [],
        "overview": {
            "description": "A world is over-run by a new type of creatures, known as Phons. They are spreading wildly. The military sends troops to ground zero, to collect a sample.\n\n\nEach player must enter ground zero. Find the sample, and get out. However it won't be that simple.",
            "features": [
                "CO-OP",
                "Voice Chat"
            ],
            "platforms": [
                "Windows",
                "Mac",
                "Linux"
            ],
            "status": "Released",
            "role": "Lead Dev",
            "storeUrl": "https://dev-stynt.itch.io/from-the-ashes-they-rise"
        },
        "details": {
            "challenges": [],
            "solutions": [],
            "lessons": [],
            "comparison": {
                "title": "",
                "items": [
                    {
                        "name": "",
                        "image": "fas fa-circle"
                    },
                    {
                        "name": "",
                        "image": "fas fa-circle"
                    }
                ],
                "analysis": {
                    "ourApproach": {
                        "title": "",
                        "description": "",
                        "whatWorked": []
                    },
                    "traditionalApproach": {
                        "title": "",
                        "description": "",
                        "whatDidntWork": []
                    }
                },
                "media": []
            }
        }
    },
    {
        "id": "displaced",
        "assetFolder": "Displaced",
        "type": "project",
        "youtubeUrls": [],
        "detailsEnabled": true,
        "title": "Displaced",
        "description": "A First Person Multiplayer FPS, fight across two dimensions to conquer reality, and survive the oncoming apocalypse.",
        "image": "fas fa-gamepad",
        "thumbnailUrl": null,
        "tech": [
            "Unity",
            "C#",
            "Substance Painter",
            "Steamworks SDK",
            "Git",
            "Blender",
            "Wwise"
        ],
        "featured": false,
        "media": [],
        "overview": {
            "description": "Displaced takes place upon two realities, fighting for control. Players must switch between these realities mid fight to obtain the best positioning advantage.",
            "features": [
                "Multiplayer, First Person Shooter",
                "Team Based, Hero Shooter",
                "Two Dimensions - One Fight",
                "Spatial audio design using Wwise"
            ],
            "platforms": [
                "PC",
                "Steam"
            ],
            "status": "In Development",
            "role": "Sole Developer",
            "storeUrl": null
        },
        "details": {
            "challenges": [
                "Networking direction. I.e. to use Peer to Peer or Servers",
                "Creating Depth of Systems or Depth of Progression. I.e. Cosmetics",
                "Large Scope while being a solo developer"
            ],
            "solutions": [
                "After attempting both, peer to peer offered the best solution to demonstrate the desired gameplay.",
                "A depth of system, such as improved platform/control support, along with better character design",
                "Develop what I can, while hiring freelancers for elements in which I lack."
            ],
            "lessons": [
                "Playtest, Playtest, Playtest!",
                "Failure does not exist, just get up, and try again.",
                "Sometimes it is ok to pivot, once you spend the time to identify if what you are doing is the right play."
            ],
            "comparison": {
                "title": "Displaced vs Traditional Survival Games",
                "items": [
                    {
                        "name": "Displaced",
                        "image": "fas fa-circle"
                    },
                    {
                        "name": "Traditional Survival",
                        "image": "fas fa-circle"
                    }
                ],
                "analysis": {
                    "ourApproach": {
                        "title": "Version 4",
                        "description": "The lessons learned both for this game, and as a developer.",
                        "whatWorked": [
                            "Systems are better when they are deep, rather than when they are wide and shallow",
                            "A good foundation, even when prototyping, means the future is expandable",
                            "Problems, similar to projects, have a scope and must be solved accordingly."
                        ]
                    },
                    "traditionalApproach": {
                        "title": "Version 1 - 3",
                        "description": "The issues and problems overcome to get to where it is today.",
                        "whatDidntWork": [
                            "Lacked focus on the core concept, including ranks and cosmetics.",
                            "Character abilities and ultimates were shallow use cases.",
                            "Rushed implementation of fundamentals (ie character movement)",
                            "Extreme amounts of Tech Debt buildup."
                        ]
                    }
                },
                "media": []
            }
        }
    }
];

const about = {
    "bullets": [
        "23 year old from Missoula, Montana.",
        "Bachelors - Management Information Systems",
        "Half a decade of game development experience.",
        "Failure gives the best opportunity to learn"
    ],
    "resumePath": "assets/Jason Firth Resume.pdf",
    "headshot": "assets/JasonHeadshot.png"
};

const experience = [
    {
        "id": "benthic-games",
        "dateRange": "May 2025 - Present",
        "title": "Contract Developer",
        "organization": "Benthic Studio (Self-employed)",
        "tech": [
            "Unity",
            "Substance Painter",
            "Steamworks SDK",
            "C#",
            "Blender",
            "FL Studio",
            "Wwise"
        ],
        "description": "Providing adaptable solutions to a variety of problems. From game development, custom software, media content, and webpages.",
        "bullets": [
            "Development from a player's perspective with a business mind ",
            "Team coordination and implementations",
            "Adaptability and drive to learn new and challenging concepts"
        ]
    },
    {
        "id": "ctk-livestream",
        "dateRange": "Sep 2021 - Present",
        "title": "Live Stream IT Consultant",
        "organization": "Christ The King Parish Missoula (Part-time)",
        "tech": [
            "Python"
        ],
        "description": "Revamped and maintained live streaming systems for a church targeting younger college audiences, building community connections beyond traditional demographics.",
        "bullets": [
            "Formed communities of unique individuals through technical solutions",
            "Problem-solved technical difficulties swiftly to avoid downtime",
            "Coordinated teams and communicated effectively for delivery"
        ]
    },
    {
        "id": "fast-enterprises",
        "dateRange": "Jun 2024 - Aug 2024",
        "title": "Implementation Consultant",
        "organization": "Fast Enterprises, LLC (Internship)",
        "tech": [
            "C#"
        ],
        "description": "Learned new systems and environments while interfacing with data and code, focusing on robust solutions for complex problems.",
        "bullets": [
            "Developed robust solutions to complex technical problems",
            "Conveyed technical information clearly to stakeholders",
            "Created accessible solutions for non-technical users"
        ]
    }
];

const CONFIG = {
    "imageTimeout": 500,
    "lazyLoadingThreshold": 0.1,
    "enableLazyLoading": true,
    "maxConcurrentLoads": 3,
    "retryAttempts": 1,
    "preloadCriticalImages": true,
    "enableImageCache": true
};

